### PR TITLE
fix: all SVGs are now inline, implement hover/focus/selected styles etc

### PR DESCRIPTION
**Pull request by cindyli**
@amb26, this PR is ready for a review. It does: 

1. Implement hover/focus/active styles;
2. Replace all background SVGs with inline SVGs;
3. Use links for a11y filter tooltip entries;
4. A few other minor tweaks.

### CODE REVIEW

**Comment by amb26** [comment]
Thanks @cindyli - This is great work.
Two small regressions wrt. trunk - 
i) The selected checkboxes are now misaligned wrt their boxes (see attached screenshot - Chrome on Windows
cindy-checkbox
)
ii) The hover styling has disappeared from the cities list

**Comment by cindyli** [comment]
Good catch, @amb26.

The issue 2 has been fixed by adding back the city list hover styling.

I cannot reproduce the issue 1. This is how these checked and focused checkboxes look like with Chrome on my Windows computer:
checkboxes

**Comment by amb26** [comment]
> I cannot reproduce the issue 1. This is how these checked and focused checkboxes look like with Chrome on my Windows computer:

I suspect you will see it if you zoom the browser - say, to 125%

**Comment by amb26** [comment]
> I suspect you will see it if you zoom the browser - say, to 125%

Sorry, ignore this - it looks like this isn't actually a regression - I can see the problem on my own system when zoomed to 125% on current Chrome, I didn't spot it since I use an old Chromium for development testing

**Comment by cindyli** [comment]
> > I suspect you will see it if you zoom the browser - say, to 125%
> 
> Sorry, ignore this - it looks like this isn't actually a regression - I can see the problem on my own system when zoomed to 125% on current Chrome, I didn't spot it since I use an old Chromium for development testing

That's all right, @amb26. It seems the issue was because checkbox-selected.svg is in a rectangular shape rather than a squared shape. Updating the SVG in the latest commit fixes the problem. Could you check please? Thanks.

**Pull request merged**
