### PR TITLE
Rationalising dependencies, with a full update as well as removing unneeded dependency on "fluid-new-renderer" - some comments TODOing needed framework improvements, and removing a logging statement

### PR DESCRIPTION
**Pull request by amb26**

### CODE REVIEW

**Comment by cindyli** [comment]
@amb26, @jobara, @greatislander: it seems removing "normalize.css` does lead to some styling issues:

1. Button default font size is smaller. It affects "reset filters" and "apply filters" buttons on the desktop view and "locations" and "accessibility filters" button on the mobile view;

More issues with the mobile styling:
1. The map is no longer from edge to edge. A small border appears around the map;
2. Probably due to the issue 1, the page no longer takes up 100% of the viewport. The page is vertically and horizontally scrollable;
3. The render of the bottom buttons and popup lists are partially offscreen.

after

When adding [the CDN version of "normalize.css"](https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css) to the page, these problems disappear.

**Comment by greatislander** [comment]
@cindyli this can likely be fixed with the following rules:

```css
body {
    margin: 0;
}

button {
    font-family: inherit;
    font-size: 100%;
}
```

However, the We Count site uses [sanitize.css](https://csstools.github.io/sanitize.css/) if I'm not mistaken, so you might want to see if that fixes the issues? If you are adding the map to the We Count site eventually it should be tested with sanitize.

**Comment by cindyli** [comment]
Shall the inclusion of `fastXmlPull.js` from the infusion lib in "index.html" at line 17 be uncommented? The map is working fine without this file. Does it mean `fastXmlPull.js` is not necessary?

**Comment by cindyli** [comment]
> @cindyli this can be fixed with the following rules:
> 
> ```css
> body {
>     margin: 0;
> }
> 
> button {
>     font-family: inherit;
>     font-size: 100%;
> }
> ```

@greatislander, thanks for the solution. Are these known issues with the removal of "normalize.css"? Is there a todo list for sites that have been using normalize.css from infusion?

**Comment by greatislander** [comment]
@cindyli Those are known issues, and the button/input sizing issue was addressed in https://github.com/fluid-project/infusion/pull/1042 for all of the Infusion components including UIO. When sites update to the latest version the UIO components will look as expected. There's not a TODO list at this time, but sites should have the body margins removed when they update.

**Comment by cindyli** [comment]
@amb26, @greatislander made a good point that the We Count website uses [sanitize.css](https://github.com/inclusive-design/wecount.inclusivedesign.ca/blob/dev/package.json#L55) for normalization. Since the map will be integrated there, we probably should add sanitize.css as a dependency and use in index.html. What do you think?

**Comment by cindyli** [comment]
BTW, I tried with having sanitize.css in the index.html. It does solve those styling issues.

**Comment by amb26** [comment]
> BTW, I tried with having sanitize.css in the index.html. It does solve those styling issues.

I found that it resolved the "more styling issues" but not the button text sizing so I have added the rule you pasted into our internal stylesheet. I've integrated sanitize.css into the internal previews of the app.
Ready for another round of review.

**Comment by cindyli** [comment]
See the screenshot: the search icon is too small; the reset query icon is not at the right position.

icons

**Comment by greatislander** [comment]
Fixes:

1. Search icon: remove the padding rule from the CSS for this element:

```css
 .fl-mapviz-query-wrapper > svg {
    height: 1.5rem;
    /* padding-left: 1rem;  Remove this line. */
    padding-top: 0.7rem;
    position: absolute;
    width: 1.5rem;
    z-index: 1;
}
```

2. Clear search (x) icon: add `display: flex` to the `.fl-mapviz-query-reset` style:

```css
.fl-mapviz-query-reset {
    height: 1rem;
    position: absolute;
    right: 0.6rem;
    top: 0.5rem;
    z-index: 900;
    display: flex;
}
```

**Comment by amb26** [comment]
> Search icon: remove the padding rule from the CSS for this element:
It's magic, but how does it work! Why does removing the padding massively increase the size of the icon?

**Comment by greatislander** [comment]
> > Search icon: remove the padding rule from the CSS for this element:
> > It's magic, but how does it work! Why does removing the padding massively increase the size of the icon?

@amb26: This all ties in to the box-sizing rule I wrote about in Element. Here's a minimal demo:

https://codepen.io/greatislander/pen/XWpGgMM

Both SVGs have a width and height of 32px, as well as a left padding value of 16px. The first one doesn't have or inherit a custom value for the [`box-sizing`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing) property, so it uses the default: `content-box`. In other words: the width attribute sets the width of the content, and padding is added outside the content. This effectively gives the first SVG a width of 32px and adds left padding of 16px outside of that width. It looks the way it ought to.

The second SVG has a `box-sizing` property set to `border-box`. In other words, the width sets the width of the element _inclusive of_ its padding. In other words, this now means that the padding value is considered to be part of the 32px width, which pads the content, squishing the icon down to half of its desired size.

Removing the padding from the SVG would fix the issue. This step is required because the reset stylesheet that the We Count project adopted sets all elements to use `box-sizing: border-box`, whereas the COVID Map was started without this rule in place. Hope that clarifies!

See also: https://css-tricks.com/box-sizing/

**Comment by amb26** [comment]
> which pads the content, squishing the icon down to half of its desired size.

Thanks for the great explanation and demo!

**Comment by cindyli** [comment]
The desktop view looks great. But the position of the search icon on the mobile view is still incorrect:

mobile

**Pull request merged**
